server:
  port: 9001
  servlet:
    context-path: /stone-test
spring:
  application:
    name: stone-test

example:
  service:
    enable: true
    suffix: ppp
    prefix: sss
aspect:
  log:
    enable: true